export interface ActiveOrderArray {
    SSNNo: number,
    OrderNo: string,
    WBS1: string,
    WBS2: string,
    WBS3: string,
    StructureElement: string,
    ProdType: string,
    PONo: string,
    PODate: string,
    RequiredDate: string,
    OrderWeight: string,
    SubmittedBy: string,
    OrderStatus: string,
    OrderSource: string,
    SONo: string,
    SORNo: string,
    BBSNo: string,
    BBSDesc: string,
    CustomerCode: string,
    ProjectCode: string,
    ProjectTitle: string,
    DataEnteredBy: string,
    Confirmed: string,
    PlanDeliveryDate: string,
    isSelected:boolean
}


// SSNNo: number,
//     OrderNo: string,
//     WBS1: string,
//     WBS2: string,
//     WBS3: string,
//     StructureElement: string,
//     ProdType: string,
//     PONo: string,
//     PODate: string,
//     RequiredDate: string,
//     OrderWeight: string,
//     SubmittedBy: string,
//     OrderStatus: string,
//     OrderSource: string,
//     SONo: string,
//     SORNo: string,
//     BBSNo: string,
//     BBSDesc: string,
//     CustomerCode: string,
//     ProjectCode: string,
//     ProjectTitle: string,
//     DataEnteredBy: string,
//     Confirmed: string,
//     PlanDeliveryDate: string