
export interface ADD_CABModel{
    VCHCABPRODUCTMARKNAME :string,
    INTSEDETAILINGID      :number,
    INTGROUPMARKID        :number,
    INTMEMBERQTY          :number,
    INTSHAPECODE          :string,
    INTPINSIZEID          :number,
    NUMINVOICELENGTH      :number,
    NUMPRODUCTIONLENGTH   :number,
    NUMINVOICEWEIGHT      :number,
    NUMPRODUCTIONWEIGHT   :number,
    GRADE                 :string,
    INTDIAMETER           :number,
    BARSTANDARD           :string,
    VCHSHAPETYPE          :string,
    VCHSHAPEGROUP         :string,
    COUPLERTYPE1          :string,
    COUPLERMATERIAL1      :string,
    COUPLERSTANDARD1      :string,
    COUPLERTYPE2          :string,   
    COUPLERMATERIAL2      :string,
    COUPLERSTANDARD2      :string,
    INTSTATUS             :string,
    VCHCUSTREMARKS        :string,
    VCHSHAPEIMAGE         :string,
    VCHCAB_BVBS           :string,
    VCHPAGENUMBER         :string, 
    VCHCOMMDESCRIPT       :string,
    NUMENVLENGTH          :number,
    NUMENVWIDTH           :number,
    NUMENVHEIGHT          :number,
    INTNOOFBENDS          :number,
    BITVARIESBAR          :any
    Shape             :any
}