export interface ColumnProduct
{
 ProductMarkId :number ,
 StructureMarkId:number ,
 ProductMarkingName :string ,
 ProductCodeId :number ,
 LinkWidth:number ,
 LinkLength:number ,
 LinkQty:number ,
 InvoiceMWQty :number ,
 InvoiceCWQty:number ,
 InvoiceMWWeight :any ,
 InvoiceCWWeight :any ,
 InvoiceWeight :any ,
 InvoiceMWLength :any ,
 InvoiceCWLength:any ,
 ShapeCodeId  :number ,
 NoofLinks  :number ,
 TotalLinks  :number ,
 MO1  :number ,
 MO2  :number ,
 CO1 :number ,
 CO2 :number ,
 ProductionMO1  :number ,
 ProductionMO2 :number ,
 ProductionCO1 :number ,
 ProductionCO2 :number ,
 InvoiceArea  :any ,
 ProductionArea :any ,
 TheoraticalWeight :any ,
 ProductionMWLength :number ,
 ProductionCWLength :number ,
 ProductionMWQty :number ,
 ProductionCWQty :number ,
 ProductionMWWeight :any ,
 ProductionCWWeight :any ,
 ProductionWeight :any ,
 PinSize :number ,
 MWSpacing:number ,
 CWSpacing:number ,
 ParamValues :string ,
 BOMDrawingPath :string ,
 MWBVBSString :string ,
 CWBVBSString :string ,
 ShapeParam:any
 ShapeCode :string ,
 Quantity :number ,
 BOMIndicator  :string ,
 CWSpacingString  :string ,
 ProduceIndicator  :any ,
 BendCheck  :any ,
 GenerationStatus :number ,
 ProductValidator:number ,
 MWPitch :string ,
 CWPitch :string ,
 MWFlag :number ,
 CWFlag :number ,

}