export interface add_drain_parameterset{
    
        tntParamSetNumber: number,
        intProjectId: number,
        sitProductTypeL2Id: number,
        vchProductType: string,
        tntTransportModeId: number,
        sitTopCover: number,
        sitBottomCover: number,
        sitLeftCover: number,
        sitRightCover: number,
        sitInnerCover: number,
        sitOuterCover: number,
        sitGap1: number,
        sitGap2: number,
        chrStandardCP: string,
        vchTransportMode: string,
        tntStatusId: number,
        intParameterSet: number,
        intMo1: number,
        intMo2: number,
        intCo1: number,
        intCo2: number,
        chrStandarCL: string,
        chrCLMaterialType: string,
        vchParameterType: string,
        bitStructureMarkingLevel: boolean,
        sitHook: number,
        sitLeg: number,
        tntRefParamSetNumber: number,
        sitMWLap: number,
        sitCWLap: number,
        sitProductTypeId: number,
        intUserId: number,
        vchDescription: string
      
}