export interface ADD_MESH_PRODUCTCODE  {
    ProductCodeId?: number,
    ProductCode?: string,
    ProductDescription?: string,
    RawMaterial?: boolean,
    MWProductCodeId?: number,
    MWMaterialType?: number,
    MWDiameter?: number,
    MWSpace?: number,
    MWGrade?: string,
    MWWeightRun?: number,
    CWProductcodeId?: number,
    CWMaterialType?: number,
    CWDiameter?: number,
    CWSpace?: number,
    CWGrade?: string,
    CWWeightRun?: number,
    WeightSqm?: number,
    TwinInd?: string,
    MinLink?: number,
    MaxLink?: number,
    SapMaterial?: number,
    ProductTypeID?: number,
    StructureElement?: string,
    StatusId?: number,
    UserId?: number
  }
