export interface AddBPC {
    CustomerCode: string,
    ProjectCode: string,
    Template: boolean,
    JobID: number,
    cage_id: number,
    pile_type: string,
    pile_dia: number,
    cage_dia: number,
    main_bar_arrange: string,
    main_bar_type: string,
    main_bar_ct: string,
    main_bar_shape: string,
    main_bar_grade: string,
    main_bar_dia: string,
    main_bar_topjoin: string,
    main_bar_endjoin: string,
    cage_length: string,
    spiral_link_type: string,
    spiral_link_grade: string,
    spiral_link_dia: string,
    spiral_link_spacing: string,
    lap_length: number,
    end_length: number,
    per_set: number,
    cage_location: string,
    rings_start: number,
    rings_end: number,
    rings_addn_no: number,
    rings_addn_member: number,
    coupler_top: string,
    coupler_end: string,
    no_of_sr: number,
    sr_grade: string,
    sr_dia: number,
    sr_dia_add: number,
    sr1_location: number,
    sr2_location: number,
    sr3_location: number,
    sr4_location: number,
    sr5_location: number,
    crank_height_top: number,
    crank_height_end: number,
    crank2_height_top: number,
    crank2_height_end: number,
    sl1_length: number,
    sl2_length: number,
    sl3_length: number,
    sl1_dia: number,
    sl2_dia: number,
    sl3_dia: number,
    total_sl_length: number,
    no_of_cr_top: number,
    cr_spacing_top: number,
    no_of_cr_end: number,
    cr_spacing_end: number,
    extra_support_bar_ind: string,
    extra_support_bar_dia: number,
    extra_cr_no: number,
    extra_cr_loc: number,
    extra_cr_dia: number,
    mainbar_length_2layer: number,
    mainbar_location_2layer: number,
    bundle_same_type: string,
    bbs_no: string,
    cage_qty: number,
    cage_weight: number,
    cage_remarks: string,
    set_code: string,
    nds_groupmarking: string,
    nds_wbs1: string,
    nds_wbs2: string,
    nds_wbs3: string,
    sor_no: string,
    sap_mcode: string,
    copyfrom_project: string,
    copyfrom_template: boolean,
    copyfrom_jobid: number,
    copyfrom_ponumber: string,
    UpdateBy: string,
    UpdateDate: string,
    cr_posn_top:number,
    cr_posn_end:number,
    cr_top_remarks:string,
    cr_end_remarks:string,
    pile_cover:number,
    pdf_remark:string,
    cr_ring_type :string,
    cr_bundle_side :string,

    sr_link_lapping ?:number,
    cr_link_lapping ?:number,
    top_link ?:any,
    vchCustomizeBarsJSON?:any,
    mainbar_position_2layer?:any,
    BPC_Type?: any,
    lminTop? : any,
    lminEnd? : any,
}
