export interface SaveAdviceJobBPC{
  CustomerCode :string,
  ProjectCode :string,
  Template :boolean,
  JobID      :number,
  PONumber :string,
  PODate     :Date,
  RequiredDate     :Date,
  Transport :string,
  OrderStatus      :string,
  TotalPcs :number,
  TotalWeight :number,
  DeliveryAddress :string,
  Remarks :string,
  SiteEngr_Name :string,
  SiteEngr_HP :string,
  SiteEngr_Tel :string,
  Scheduler_Name :string,
  Scheduler_HP :string,
  Scheduler_Tel :string,
  cover_to_link :number,
  underload_ct :number,
  redesign_req :number,
  pile_category :string,
  OrderSource :string,
  UpdateDate :Date,
  UpdateBy :string,
}
