
export interface CABOrderDetailsModel {
    CustomerCode: string,
    ProjectCode: string,
    JobID: number,
    PONumber: string,
    PODate: string,
    RequiredDate: string,
    CouplerType: string,
    OrderStatus: string,
    TotalCABWeight: number,
    TotalSTDWeight: number,
    TotalWeight: number,
    TransportLimit: string,
    TransportMode: string,
    Scheduler_HP: string,
    Scheduler_Name: string,
    Scheduler_Tel: string,
    SiteEngr_HP: string,
    SiteEngr_Name: string,
    SiteEngr_Tel: string,
    WBS1: string,
    WBS2: string,
    WBS3: string,
    ProjectStage: string,
    DeliveryAddress: string,
    Remarks: string,
    UpdateDate: string,
    OrderSource: string,
    Exists: number,
    BBSStandard: string
}