export interface CappingInfoList {
    CAPPRODUCT: number,
    SHAPECODE: number,
    WIDTH: number,
    DEPTH: number,
    COUNT: number,
    TYPE: number,
    STRUCTUREELEMENT: number,
    MWLENGTH: number,
    CWQTY: number,
    MO1: number,
    MO2: number,
    CWSPACE: number,
    MWSPACE: number,
    LENGTH: number,
    CO1: number,
    CO2: number,
    MWQTY: number,
    INVOICEMWWEIGHT: number,
    INVOICECWWEIGHT: number,
    THEORITICALWEIGHT: number,
    AREA: number,
    SMID: number,
    PMID: number
}