export interface DeliveredOrderArray {
    
        SSNO:number,
        PONo: string,
        WBS1: string,
        WBS2: string,
        WBS3: string,
        StructureElement: string,
        ProdType: string,
        PODate: string,
        RequiredDate: string,
        OrderWeight: string,
        LoadQty: string,
        LoadWT: string,
        DeliveryDate: string,
        TransportMode: string,
        VehicleNo: string,
        OutTime: string,
        DigiOSID: number,
        DONo: string,
        BBSNo: string,
        BBSDesc: string,
        CustomerCode: string,
        ProjectCode: string,
        ProjectTitle: string,
        PartialDelivery: boolean,
        rowSelected:boolean,
        SubmittedBy:string;
      
}


// SSNNo: number,
//     OrderNo: string,
//     WBS1: string,
//     WBS2: string,
//     WBS3: string,
//     StructureElement: string,
//     ProdType: string,
//     PONo: string,
//     PODate: string,
//     RequiredDate: string,
//     OrderWeight: string,
//     SubmittedBy: string,
//     OrderStatus: string,
//     OrderSource: string,
//     SONo: string,
//     SORNo: string,
//     BBSNo: string,
//     BBSDesc: string,
//     CustomerCode: string,
//     ProjectCode: string,
//     ProjectTitle: string,
//     DataEnteredBy: string,
//     Confirmed: string,
//     PlanDeliveryDate: string