export interface Drain_WM{
    intDrainWMId: number,
    tntParamSetNumber: number,
    vchDrainType: string,
    vchDrainLayer: string,
    intDrainDepthParamId: number,
    sitDrainWidth: number,
    sitMaxDepth: number,
    vchProductCode: string,
    chrShapeCode: string,
    numLeftWallThickness: number,
    numLeftWallFactor: number,
    numRightWallThickness: number,
    numRightWallFactor: number,
    numBaseThickness: number,
    numMainLength: number,
    intQty: number,
    bitPreDefined: boolean,
    intShapeId: number,
    intProductCodeId: number,
    intParamA: number,
    sitDrainTypeId: number,
    tntDrainLayerId: number,
    bitDetail: boolean,
    intUserId: number
}