export interface GenerateOtherDrainProduct{
    
        strProductMarkName: string,
        vchMeshShape: string,
        intShapeId: number,
        strMWLen: string,
        strCWLen: string,
        strMWSpace: string,
        strCWSpace: string,
        strMWDia: string,
        strCWDia: string,
        strMO1: string,
        strMO2: string,
        strCO1: string,
        strCO2: string,
        strProductMarkId: string,
        intStructureMarkId: number,
        strProductCodeId: string,
        blnTC: boolean,
        blnBC: boolean,
        blnMC: boolean,
        strShapeCode: string,
        strProductCode: string,
        intTransHeaderId: number,
        TotMeshQty: number,
        strSequence: string,
        strParamValues: string,
        strCriticalIndicator: string,
        intParameterSet: number,
        tntStructureRevNo: number,
        strUserId: string,
        strPrdInd: string,
        bitOHVal: string
      
}