
export interface Insert_BPC_Structuremarking_Temp{

        intSEDetailingId: number,
        vchStructureMarkingName: string,
        tntStructureRevNo: number,
        intSAPMaterialCodeId: number,
        intGroupMarkId: number,
        tntGroupRevNo: number,
        tntParamSetNumber: number,
        intNoofWeldPoints: number,
        intShenellTemplateId: number,
        vchShenellAlternateTemplates: string,
        numPileDia: number,
        numCageLength: number,
        numCageDia: number,
        vchFabricationType: string,
        vchMainBarPattern: string,
        vchElevationPattern: string,
        tntNumOfMainBar: number,
        tntNumOfLinksatStart: number,
        tntNumOfLinksatEnd: number,
        tntAdditionalSpiral: number,
        tntNumberOfStiffnerOrCentralizer: number,
        tntNumOfSquareStiffner: number,
        tntNumOfCircularRings: number,
        intLapLength: number,
        intEndLength: number,
        intCoverToLink: number,
        intAjustmentFactor: number,
        bitCageNoteChangeIndicator: boolean,
        tntCageNoteId: number,
        vchCageNote: string,
        MachineTypeId: number,
        intMemberQty: number,
        numNetWeight: number,
        numActualWeight: number,
        vchDrawingReference: string,
        chrDrawingVersion: string,
        vchDrawingRemarks: string,
        vchTactonConfigurationState: string,
        vchHoleConfigurationXML: string,
        vchTactonXmlResult: string,
        bitAssembly: boolean,
        bitGenerate3DforPreview: boolean,
        nvchEdwgPath: string,
        chrGeneration3DStatus: string,
        vchOutputDrawingRef: string,
        bitCoat: boolean,
        vchMainBarDia: string,
        vchLinkDia: string,
        vchLinkPitch: string,
        tntStatusId: number,
        intCreatedUId: number,
        intUploadedUId: number,
        vchPDFPath: string,
        //--------------------------//
        intCageDia: number,
        intMachineTypeId: number,
        vch3DImageRef: any,
        vchBPCPdfPath:any,
        numStructActualWeight:any,
        intCreatedUID:any,
        intUpdatedUID:any,
        sitProductTypeId:any,
        intSmallerMainBarLength:any,
        intBPCMaterialCodeID: any
      
    }