export interface JobAdviceModels {
    CustomerCode :string,
    ProjectCode :string,
    JobID : number,
    // PONumber :string,
    // PODate : Date,
    // RequiredDate : Date,
    CouplerType :string,
    // OrderStatus :string,
    TotalCABWeight :number,
    TotalSTDWeight :number,
    TotalWeight :number,
    TransportLimit :string,
    // SiteEngr_Name :string,
    // SiteEngr_HP :string,
    // SiteEngr_Tel :string,
    // Scheduler_Name :string,
    // Scheduler_HP :string,
    // Scheduler_Tel :string,
    // WBS1 :string,
    // WBS2 :string,
    // WBS3 :string,
    // DeliveryAddress :string,
    // ProjectStage :string,
    // Remarks :string,
    // OrderSource :string,
    // TransportMode :string,
    BBSStandard :string,
    // UpdateDate :Date,
    // UpdateBy :string
}


// SSNNo: number,
//     OrderNo: string,
//     WBS1: string,
//     WBS2: string,
//     WBS3: string,
//     StructureElement: string,
//     ProdType: string,
//     PONo: string,
//     PODate: string,
//     RequiredDate: string,
//     OrderWeight: string,
//     SubmittedBy: string,
//     OrderStatus: string,
//     OrderSource: string,
//     SONo: string,
//     SORNo: string,
//     BBSNo: string,
//     BBSDesc: string,
//     CustomerCode: string,
//     ProjectCode: string,
//     ProjectTitle: string,
//     DataEnteredBy: string,
//     Confirmed: string,
//     PlanDeliveryDate: string