export interface OrderDetailsRetModels {
    CustomerCode : string,
    ProjectCode :string,
    JobID :number,
    BBSID :number,
    BarID :number,
    BarSort :number,
    Cancelled :boolean,
    ElementMark :string
    BarMark :string,
    BarType :string,
    BarSize :number
    BarCAB :boolean
    BarSTD :boolean
    BarMemberQty :number,
    BarEachQty :number,
    BarTotalQty :number,
    BarShapeCode :string,
    A :number,
    B :number,
    C :number,
    D :number,
    E :number,
    F :number,
    G :number,
    H :number,
    I :number,
    J :number,
    K :number,
    L :number,
    M :number,
    N :number,
    O :number,
    P :number,
    Q :number,
    R :number,
    S :number,
    T :number,
    U :number,
    V :number,
    W :number,
    X :number,
    Y :number,
    Z :number,
    A2 :number,
    B2 :number,
    C2 :number,
    D2 :number,
    E2 :number,
    F2 :number,
    G2 :number,
    H2 :number,
    I2 :number,
    J2 :number,
    K2 :number,
    L2 :number,
    M2 :number,
    N2 :number,
    O2 :number,
    P2 :number,
    Q2 :number,
    R2 :number,
    S2 :number,
    T2 :number,
    U2 :number,
    V2 :number,
    W2 :number,
    X2 :number,
    Y2 :number,
    Z2 :number,
    BarLength :number,
    BarLength2 :number,
    BarWeight :number,
    Remarks :string,
    shapeParameters :string,
    shapeLengthFormula :string,
    shapeParaValidator :string,
    shapeTransportValidator :string,
    shapeParType :string,
    shapeDefaultValue :string,
    shapeHeightCheck :string,
    shapeTransport :number,
    //null ; 0 -- normal 1 -- Low Bed 2 -- Low Bed wirh police escort
     PinSize :number,
    UpdateDate :Date
}


// SSNNo: number,
//     OrderNo: string,
//     WBS1: string,
//     WBS2: string,
//     WBS3: string,
//     StructureElement: string,
//     ProdType: string,
//     PONo: string,
//     PODate: string,
//     RequiredDate: string,
//     OrderWeight: string,
//     SubmittedBy: string,
//     OrderStatus: string,
//     OrderSource: string,
//     SONo: string,
//     SORNo: string,
//     BBSNo: string,
//     BBSDesc: string,
//     CustomerCode: string,
//     ProjectCode: string,
//     ProjectTitle: string,
//     DataEnteredBy: string,
//     Confirmed: string,
//     PlanDeliveryDate: string