export interface OrdersForAmendment {
    CustomerCode: string,
    ProjectCode: string,
    RDateFrom: string,
    RDateTo: string,
    SORNofrom: string,
    SORNoTo: string,
    WBS1: string,
    WBS2: string,
    WBS3: string,
    SearchOptions: string,
    txtSearch: string,
    SO_SOR_Search_Range: string,
    Req_PO_Date_Search_Range: string,
    Rev_required_Conf_date_from: string,
    Rev_required_Conf_date_to: string,
    Rev_Req_Confirmed_Date_Search_Range: string,
    SearchProducts: string,
    SearchOptionsByDesignation: string,
    lSearchByDesignation: string
}



//     OrderNo: string,
//     WBS1: string,
//     WBS2: string,
//     WBS3: string,
//     StructureElement: string,
//     ProdType: string,
//     PONo: string,
//     PODate: string,
//     RequiredDate: string,
//     OrderWeight: string,
//     SubmittedBy: string,
//     OrderStatus: string,
//     OrderSource: string,
//     SONo: string,
//     SORNo: string,
//     BBSNo: string,
//     BBSDesc: string,
//     CustomerCode: string,
//     ProjectCode: string,
//     ProjectTitle: string,
//     DataEnteredBy: string,
//     Confirmed: string,
//     PlanDeliveryDate: string