export interface SaveJobAdvice_CAB {
    CustomerCode: string,
    ProjectCode: string,
    JobID: number,
    PONumber: string,
    PODate: Date,
    RequiredDate: Date,
    CouplerType: string,
    OrderStatus: string,
    TotalCABWeight: number,
    TotalSTDWeight: number,
    TotalWeight: number,
    TransportLimit: string,
    SiteEngr_Name: string,
    SiteEngr_HP: string,
    SiteEngr_Tel: string,
    Scheduler_Name: string,
    Scheduler_HP: string,
    Scheduler_Tel: string,
    WBS1: string,
    WBS2: string,
    WBS3: string,
    DeliveryAddress: string,
    ProjectStage: string,
    Remarks: string,
    OrderSource: string,
    TransportMode: string,
    BBSStandard: string,
    UpdateDate: Date,
    UpdateBy: string
  }
 