export interface saveOrderDetailsModel {
    pOrderHeader: {
        OrderNumber: number,
        CustomerCode: string,
        ProjectCode: string,
        OrderJobID: number,
        OrderType: string,
        WBS1: string,
        WBS2: string,
        WBS3: string,
        Remarks: string,
        DeliveryAddress: string,
        SiteEngr_Name: string,
        SiteEngr_HP: string,
        SiteEngr_Email: string,
        Scheduler_Name: string,
        Scheduler_HP: string,
        Scheduler_Email: string,
        TotalWeight: number,
        OrderStatus: string,
        OrderSource: string,
        PONumber: string,
        PODate: Date,
        RequiredDate: Date,
        OrigReqDate: Date,
        TransportMode: string,
        UpdateDate: Date,
        UpdateBy: string,
        SubmitDate: Date,
        SubmitBy: string,
        OrderShared: true,
        Address:string | null,
        Gate:string | null
    },
    pOrderCart: [
        {
            OrderNumber: Number,
            StructureElement: string,
            ProductType: string,
            ScheduledProd: string,
            PONumber: string,
            PODate: Date,
            RequiredDate: Date,
            OrigReqDate: Date,
            TransportMode: string,
            CABJobID: number,
            MESHJobID: number,
            BPCJobID: number,
            CageJobID: number,
            CarpetJobID: number,
            StdBarsJobID: number,
            StdMESHJobID: number,
            CoilProdJobID: number,
            PostHeaderID: number,
            OrderStatus: string,
            TotalWeight: number,
            TotalPCs: number,
            SAPSOR: string,
            UpdateBy: string,
            UpdateDate: Date,
            ProcessBy: string,
            ProcessDate: Date,
            SpecialRemark: string,
            SiteContact: string,
            Handphone: string,
            GoodsReceiver: string,
            GoodsReceiverHandphone: string
            AdditionalRemark:string
        }
    ]
}

