export interface SlabShapeParameter {
   
INTSHAPEID:number,
CHRPARAMNAME:any,
CHRCRITICALIND:any,
INTPARAMSEQ:any,	
CHRSHAPECODE:any,	
BITEDIT	:any,
CHRANGLETYPE	:any,
BITVISIBLE	:any,
CHRWIRETYPE	:any,
BITOHDTLS	:any,
DEFAULTPARAMVALUE:any,
SITEVENMO1	:any,
SITEVENMO2	:any,
SITODDMO1	:any,
SITODDMO2	:any,
SITEVENCO1	:any,
SITEVENCO2	:any,
SITODDCO1	:any,
SITODDCO2	:any,
BITDEFAULTOHINDICATOR:any,
INTANGLEDIR:any
}
