export interface SubmitProcessModel {
  CustomerCode: string,
  ProjectCode: string,
  ContractNo: string,
  ProdType: string,
  JobID: number,
  CashPayment: string,
  CABFormer: string,
  ShipToParty: string,
  ProjectStage: string,
  ReqDateFrom: string | null,
  ReqDateTo: string | null,
  PONumber: string,
  PODate: string | null,
  WBS1: string,
  WBS2: string,
  WBS3: string,
  VehicleType: string,
  UrgentOrder: boolean,
  Conquas: boolean,
  Crane: boolean,
  PremiumService: boolean,
  ZeroTol: boolean,
  CallBDel: boolean,
  DoNotMix: boolean,
  SpecialPass: boolean,
  VehLowBed: boolean,
  Veh50Ton: boolean,
  Borge: boolean,
  PoliceEscort: boolean,
  TimeRange: string,
  IntRemarks: string,
  ExtRemarks: string,
  OrderSource: string,
  StructureElement: string,
  ScheduledProd: string,
  OrderType: string,
  InvRemarks: string,
  FabricateESM: boolean,
  UserName:string,
  UserType: string,
  IsGreensteel:string
}
