export interface UpdateProcessSORModel {
    CustomerCode: string,
    ProjectCode: string,
    ContractNo: string,
    ProdType: string,
    JobID: number,
    SOR: string,
    CashPayment: string,
    ProjectStage: string,
    ReqDateFrom: string | null,
    ReqDateTo: string | null,
    PONumber: string,
    PODate: string | null,
    WBS1: string,
    WBS2: string,
    WBS3: string,
    VehicleType: string,
    UrgentOrder: boolean,
    Conquas: boolean,
    Crane: boolean,
    PremiumService: boolean,
    ZeroTol: boolean,
    CallBDel: boolean,
    DoNotMix: boolean,
    SpecialPass: boolean,
    VehLowBed: boolean,
    Veh50Ton: boolean,
    Borge: boolean,
    PoliceEscort: boolean,
    TimeRange: string,
    IntRemarks: string,
    ExtRemarks: string,
    InvRemarks: string,
    OrderSource: string,
    StructureElement: string,
    ScheduledProd: string,
    ChReqDate: number,
    ChPONumber: number,
    ChVehicleType: number,
    ChBookInd: number,
    ChBBSNo: number,
    ChBBSDesc: number,
    ChIntRemakrs: number,
    ChExtRemakrs: number,
    ChInvRemakrs: number,
    OrderStatus: string,
    FabricateESM: boolean,
    strMastReqDate: string,
    strUrgOrd: string,
    strIntRemark: string,
    strExtRemark: string,
    strPremiumSvc: string,
    strCraneBooked: string,
    strBargeBooked: string,
    strPoliceEscort: string,
    strZeroTol: string,
    strCallBefDel: string,
    strConquas: string,
    strSpecialPass: string,
    strLorryCrane: string,
    strLowBedVeh: string,
    strDoNotMix: string,
    strOnHold: string,
    str50TonVeh: string,
    strBBSNo: string,
    strItemReqDate: string,
    UserName:string
}



// {
//   CustomerCode: "0001101200",
//   ProjectCode: "0000111613",
//   ContractNo: "1020018184",
//   ProdType: "STANDARD-MESH",
//   JobID: 284610,
//   SOR: "",
//   CashPayment: "N",
//   ProjectStage: "TYP",
//   ReqDateFrom: "2023-10-19",
//   ReqDateTo: "2023-08-31",
//   PONumber: "CCKN1C16PO2047-22963",
//   PODate: "2023-07-07",
//   WBS1: "C3A",
//   WBS2: "1",
//   WBS3: "",
//   VehicleType: "TR40/24",
//   UrgentOrder: false,
//   Conquas: true,
//   Crane: true,
//   PremiumService: true,
//   ZeroTol: true,
//   CallBDel: true,
//   DoNotMix: true,
//   SpecialPass: true,
//   VehLowBed: true,
//   Veh50Ton: true,
//   Borge: true,
//   PoliceEscort: true,
//   TimeRange: "string",
//   IntRemarks: "71A TUAS NEXUS DRIVE, S 636748 /ZHANG TIAH  ZE 85243292/AUNG 94562691/ 1ST PART 2 BASE SLAB BAR CH",
//   ExtRemarks: "71A TUAS NEXUS DRIVE, S 636748 /ZHANG TIAH  ZE 85243292/AUNG 94562691/ 1ST PART 2 BASE SLAB BAR CH",
//   InvRemarks: "string",
//   OrderSource: "UX",
//   StructureElement: "NONWBS",
//   ScheduledProd: "N",
//   ChReqDate: 0,
//   ChPONumber: 1,
//   ChVehicleType: 0,
//   ChBookInd: 0,
//   ChBBSNo: 0,
//   ChBBSDesc: 0,
//   ChIntRemakrs: 0,
//   ChExtRemakrs: 0,
//   ChInvRemakrs: 0,
//   OrderStatus: "Submitted",
//   FabricateESM: true,
//   strMastReqDate: "string",
//   strUrgOrd: "string",
//   strIntRemark: "string",
//   strExtRemark: "string",
//   strPremiumSvc: "string",
//   strCraneBooked: "string",
//   strBargeBooked: "string",
//   strPoliceEscort: "string",
//   strZeroTol: "string",
//   strCallBefDel: "string",
//   strConquas: "string",
//   strSpecialPass: "string",
//   strLorryCrane: "string",
//   strLowBedVeh: "string",
//   strDoNotMix: "string",
//   strOnHold: "string",
//   str50TonVeh: "string",
//   strBBSNo: "string",
//   strItemReqDate: "string"

// }