import { wbsposting_groupmark } from "./wbsposting_groupmark"

export interface wbsPosting { 
    INTWBSELEMENTID: number,
    ORD_REQ_NO: string,
    VCHWBS1: string,
    VCHWBS2: string,
    VCHWBS3: string,
    StructureElementID: number,
    StructureElement: string,
    ProductTypeID: number,
    ProductType: string
    TOTALWEIGHT: number,
    TOTALQTY: number,
    VCHBBSNO: string,
    BBS_DESC: string,
    POSTEDBY: string,
    DATPOSTEDDATE: string,
    INTRELEASEBY: string,
    DATRELEASEDDATE: string,
    TNTSTATUSID: number,
    INTPOSTHEADERID: number,
    CHRSTATUSCODE: string,
    IDENTITY_NO: string,
    ReqDate: string,
    SOReqDetailsId: number,
    isSelected: boolean,
    ReadOnly: boolean,
    isposted: boolean, 
    isreleased: boolean, 
    iscreated: boolean, 
    isdetailing: boolean,
    isExpand:boolean,
    Groupmarkinglist: wbsposting_groupmark[]

    }
  
    // "INTWBSELEMENTID": 487,
    // "ORD_REQ_NO": "0000021221",
    // "VCHWBS1": "SB-TEST",
    // "VCHWBS2": "1",
    // "VCHWBS3": "SB-TEST",
    // "StructureElementID": 3,
    // "ProductTypeID": 9,
    // "TOTALWEIGHT": 0,
    // "TOTALQTY": 0,
    // "VCHBBSNO": "ENINH34569M",
    // "BBS_DESC": "0.137",
    // "POSTEDBY": "Archived 06 (NatSteel)",
    // "DATPOSTEDDATE": "11/04/2009 15:00:25",
    // "INTRELEASEBY": "Luzviminda Espinal Alger (NatSteel)",
    // "DATRELEASEDDATE": "11/06/2009 15:00:47",
    // "TNTSTATUSID": 12,
    // "INTPOSTHEADERID": 112,
    // "CHRSTATUSCODE": "Ca",
    // "IDENTITY_NO": "71",
    // "ReqDate": "11-11-2009"